name = "dimonium-auto-comment"
main = "src/consumer.ts"
compatibility_date = "2025-06-09"
node_compat = true

[[queues.producers]]
binding = "COMMENT_QUEUE"
queue = "comment-queue"

[[queues.consumers]]
queue = "comment-queue"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 2
