name = "dimon-comment"
main = "src/commentProcessor.ts"
compatibility_date = "2025-06-09"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "COMMENT_KV"
id = "e9852af456e6491bbc762f0a568514bc"

[[triggers]]
crons = ["*/1 * * * *"]
