name = "dimonium-auto-comment"
main = "src/consumer.ts"
compatibility_date = "2025-06-09"

[[queues.producers]]
binding = "COMMENT_QUEUE"
queue = "comment-queue"

[[queues.consumers]]
queue = "comment-queue"

[vars]
LANGUAGES = "en,fa,ru,es,hi"
