# .github/workflows/clear-comments.yml
name: Clear All Comments

on:
  workflow_dispatch:

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Run clearComments script
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
        run: pnpm tsx scripts/clearComments.ts
