name: Populate Queue
on:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm tsx src/producer.ts
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
