name: Auto-Populate

on:
  schedule:
    - cron: '0 */3 * * *'   
  workflow_dispatch:         
  push:                      
    branches:
      - main
    paths:
      - '**/*.ts'
      - 'data/**'
      - '.github/workflows/populate.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  populate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install

      - name: Populate Queue
        run: pnpm populate
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_USERS: ${{ secrets.YOUTUBE_USERS }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
          GH_CONTENTS_TOKEN: ${{ secrets.GH_CONTENTS_TOKEN }}
